package com.li_routi.feature.mypage.component

/** [PolicyTextScreen][com.li_routi.feature.mypage.screen.PolicyTextScreen] 한 줄의 글자 스타일. */
enum class PolicyLineStyle { Title, Heading, Body }

/**
 * 정책/약관 화면 본문 한 줄. 빈 문단(Figma의 zero-width-space 빈 줄)도 [PolicyLineStyle.Body]에
 * 빈 문자열로 그대로 옮겨서 원본과 같은 줄 간격을 유지한다.
 */
data class PolicyLine(val text: String, val style: PolicyLineStyle = PolicyLineStyle.Body)

/** [PolicyLine] 목록을 순서대로 적어 내려가기 위한 작은 빌더. */
private class PolicyLinesBuilder {
    private val lines = mutableListOf<PolicyLine>()

    fun title(text: String) {
        lines += PolicyLine(text, PolicyLineStyle.Title)
    }

    fun heading(text: String) {
        lines += PolicyLine(text, PolicyLineStyle.Heading)
    }

    fun body(text: String = "") {
        lines += PolicyLine(text, PolicyLineStyle.Body)
    }

    fun build(): List<PolicyLine> = lines
}

private fun policyLines(builder: PolicyLinesBuilder.() -> Unit): List<PolicyLine> =
    PolicyLinesBuilder().apply(builder).build()

/** 이용약관. Figma node `6008:18193`. */
val TermsOfServiceLines: List<PolicyLine> = policyLines {
    title("리루티 이용약관")
    body()
    body("시행일: 2026년 8월 21일")
    body()
    heading("제1조 목적")
    body()
    body("본 약관은 리루티 운영팀이 제공하는 리루티 서비스의 이용과 관련하여 서비스와 회원의 권리, 의무 및 책임 사항을 정하는 것을 목적으로 합니다.")
    body()
    heading("제2조 용어의 정의")
    body()
    body("1. \"서비스\"란 일상의 루틴을 기록하고 다른 회원과 함께 이어갈 수 있도록 리루티가 제공하는 기능을 말합니다.")
    body("2. \"회원\"이란 본 약관에 동의하고 소셜 계정을 통해 서비스에 가입한 이용자를 말합니다.")
    body("3. \"인증물\"이란 회원이 루틴 수행을 인증하기 위해 등록한 사진과 관련 내용을 말합니다.")
    body("4. \"앱 내 재화\"란 서비스 이용 과정에서 지급하거나 사용할 수 있는 다이아, 토파즈 등의 가상 재화를 말합니다.")
    body("5. 본 약관에서 정하지 않은 용어는 서비스 화면과 개별 운영정책에서 안내하는 의미를 따릅니다.")
    body()
    heading("제3조 약관의 적용 및 변경")
    body()
    body("1. 본 약관은 회원이 가입 과정에서 동의한 때부터 적용됩니다.")
    body("2. 리루티 운영팀은 관련 법령을 위반하지 않는 범위에서 약관을 변경할 수 있습니다.")
    body("3. 약관을 변경하는 경우 적용일과 변경 사유를 서비스 내 공지사항을 통해 안내합니다.")
    body("4. 일반적인 변경 사항은 적용일 7일 전부터 안내하며, 회원에게 불리하거나 중요한 변경 사항은 적용일 30일 전부터 안내합니다.")
    body("5. 변경된 약관은 안내한 적용일부터 효력이 발생합니다.")
    body()
    heading("제4조 회원가입 및 계정 관리")
    body()
    body("1. 만 14세 미만인 사람은 서비스에 가입할 수 없습니다.")
    body("2. 회원은 본인의 소셜 계정을 이용하여 가입해야 하며, 다른 사람의 계정이나 정보를 사용해서는 안 됩니다.")
    body("3. 회원은 자신의 계정이 부정하게 사용되지 않도록 합리적인 주의를 기울여야 합니다.")
    body("4. 계정의 도용이나 부정 사용을 확인한 경우 회원은 즉시 앱 내 \"문의하기\"를 통해 알려야 합니다.")
    body("5. 중복 가입, 다른 사람의 정보 사용 또는 정상적인 가입 절차를 우회한 사실이 확인되면 가입이나 서비스 이용이 제한될 수 있습니다.")
    body()
    heading("제5조 서비스의 제공")
    body()
    body("리루티는 다음과 같은 기능을 제공합니다.")
    body()
    body("1. 개인 및 공동 루틴 생성과 관리")
    body("2. 사진을 이용한 루틴 인증")
    body("3. 친구 및 그룹 구성원과의 루틴 공유")
    body("4. 인증 현황 확인과 쿡쿡 등의 상호작용")
    body("5. 앱 내 재화와 보상 기능")
    body("6. 그 밖에 리루티 운영팀이 제공하는 관련 기능")
    body()
    heading("제6조 서비스의 변경 및 중단")
    body()
    body("1. 리루티 운영팀은 서비스 개선, 점검, 운영상 또는 기술상 필요에 따라 기능의 전부 또는 일부를 변경할 수 있습니다.")
    body("2. 서비스 내용이나 이용 방법이 중요하게 변경되는 경우 적용 전에 공지사항을 통해 안내합니다.")
    body("3. 점검, 통신 장애, 재난 또는 그 밖에 합리적으로 통제하기 어려운 사유가 발생하면 서비스 제공이 일시적으로 중단될 수 있습니다.")
    body("4. 긴급한 장애 대응처럼 사전에 안내하기 어려운 경우에는 조치 후 가능한 한 빠르게 안내합니다.")
    body()
    heading("제7조 회원의 의무")
    body()
    body("회원은 다음 행위를 해서는 안 됩니다.")
    body()
    body("1. 다른 사람의 계정이나 정보를 도용하는 행위")
    body("2. 허위 또는 반복적인 인증물을 등록하는 행위")
    body("3. 다른 사람의 사진이나 콘텐츠를 허락 없이 사용하는 행위")
    body("4. 다른 사람의 개인정보, 초상권, 저작권 또는 그 밖의 권리를 침해하는 행위")
    body("5. 욕설, 혐오 표현, 음란물, 폭력적 내용, 광고 또는 도배성 콘텐츠를 등록하는 행위")
    body("6. 서비스의 정상적인 운영을 방해하거나 재화를 부정하게 획득하는 행위")
    body("7. 관련 법령, 본 약관 또는 개별 운영정책을 위반하는 행위")
    body()
    heading("제8조 회원 콘텐츠 및 자동 검토")
    body()
    body("1. 회원이 작성하거나 등록한 콘텐츠의 권리는 원칙적으로 해당 회원에게 있습니다.")
    body("2. 회원은 자신이 등록하는 콘텐츠에 필요한 권리를 보유하거나 적법한 이용 권한을 가지고 있어야 합니다.")
    body("3. 리루티는 루틴 공유, 인증 현황 표시, 신고 처리 등 서비스 제공에 필요한 범위에서 회원의 콘텐츠를 저장하고 표시할 수 있습니다.")
    body("4. 등록된 인증물은 해당 루틴과 관련된 사진인지 확인하기 위해 자동화된 방식으로 검토될 수 있습니다.")
    body("5. 자동 검토 결과에 이의가 있는 회원은 앱 내 \"문의하기\"를 통해 재검토를 요청할 수 있습니다.")
    body("6. 개인정보 처리와 자동 검토에 관한 자세한 내용은 개인정보 처리방침에서 안내합니다.")
    body()
    heading("제9조 신고 및 운영 조치")
    body()
    body("1. 회원은 운영 기준을 위반한 것으로 의심되는 인증물을 서비스에서 제공하는 신고 기능을 통해 신고할 수 있습니다.")
    body("2. 신고된 인증물은 신고 누적 기준에 따라 일부 또는 전체 회원에게 숨김 처리될 수 있습니다.")
    body("3. 운영 기준을 위반하거나 다른 사람의 권리를 침해한 콘텐츠에는 숨김, 삭제 또는 그 밖에 필요한 조치가 적용될 수 있습니다.")
    body("4. 신고 기준과 처리 방법에 관한 자세한 내용은 신고 및 운영 정책에서 안내합니다.")
    body()
    heading("제10조 앱 내 재화")
    body()
    body("1. 현재 데모 서비스에서는 실제 금액을 결제하는 유료 충전 기능을 제공하지 않습니다.")
    body("2. 데모에서 지급되는 앱 내 재화는 서비스 안에서만 사용할 수 있으며 현금으로 교환하거나 환불받을 수 없습니다.")
    body("3. 오류나 부정한 방법으로 획득한 재화는 회수될 수 있습니다.")
    body("4. 앱 내 재화의 지급, 사용, 소멸 및 환불에 관한 자세한 내용은 코인 및 환불 정책에서 안내합니다.")
    body()
    heading("제11조 회원 탈퇴")
    body()
    body("1. 회원은 서비스에서 제공하는 회원 탈퇴 기능을 이용하여 언제든지 탈퇴할 수 있습니다.")
    body("2. 탈퇴 시 회원의 개인정보와 이용 기록은 개인정보 처리방침에 따라 처리됩니다.")
    body("3. 공동 루틴의 수행 여부와 날짜처럼 다른 회원의 이용 기록과 연결된 정보는 작성자를 식별할 수 없도록 처리한 뒤 남을 수 있습니다.")
    body("4. 회원이 직접 삭제할 수 있는 콘텐츠는 탈퇴 전에 삭제하는 것을 권장합니다. 직접 처리하기 어려운 경우 앱 내 \"문의하기\"를 통해 요청할 수 있습니다.")
    body("5. 탈퇴와 동시에 보유한 앱 내 재화는 소멸하며 복구되지 않습니다.")
    body()
    heading("제12조 책임의 제한")
    body()
    body("1. 리루티 운영팀은 천재지변, 통신 장애, 외부 서비스 장애 또는 그 밖에 합리적으로 통제하기 어려운 사유로 서비스를 제공할 수 없는 경우 그에 대한 책임이 제한될 수 있습니다.")
    body("2. 회원의 귀책사유로 발생한 서비스 이용 장애에 대해서는 리루티 운영팀의 책임이 제한될 수 있습니다.")
    body("3. 회원이 등록한 콘텐츠나 회원 간 상호작용에서 발생한 분쟁은 해당 회원이 책임지고 해결하는 것을 원칙으로 합니다. 다만 리루티 운영팀은 신고 접수 등 서비스에서 제공하는 범위의 조치를 할 수 있습니다.")
    body("4. 본 조는 관련 법령에 따라 리루티 운영팀이 부담해야 하는 책임을 배제하지 않습니다.")
    body()
    heading("제13조 준거법, 분쟁 해결 및 문의")
    body()
    body("1. 본 약관과 서비스 이용에는 대한민국 법령을 적용합니다.")
    body("2. 서비스 이용과 관련한 분쟁이 발생한 경우 회원과 리루티 운영팀은 원만한 해결을 위해 노력합니다.")
    body("3. 해결되지 않은 분쟁은 관련 법령에서 정한 절차와 관할 법원에 따릅니다.")
    body("4. 서비스 이용과 관련한 문의는 앱 내 \"문의하기\" 또는 liroutisupport@gmail.com을 통해 접수할 수 있습니다.")
    body()
    body("부칙")
    body()
    body("본 약관은 2026년 8월 21일부터 시행합니다.")
}

/** 개인정보 처리방침. Figma node `6008:17998`. */
val PrivacyPolicyLines: List<PolicyLine> = policyLines {
    title("리루티 개인정보 처리방침")
    body()
    body("시행일: 2026년 8월 21일")
    body()
    body("리루티 운영팀은 회원의 개인정보를 중요하게 생각하며, 서비스 제공에 필요한 범위에서 개인정보를 처리합니다. 본 개인정보 처리방침은 어떤 정보를 왜 처리하고, 얼마나 보관하며, 회원이 어떤 권리를 행사할 수 있는지 안내합니다.")
    body()
    heading("1. 개인정보의 처리 목적")
    body()
    body("리루티 운영팀은 다음 목적을 위해 개인정보를 처리합니다.")
    body()
    body("1) 회원가입, 소셜 로그인 및 회원 식별")
    body("2) 개인·공동 루틴의 생성과 관리")
    body("3) 사진을 이용한 루틴 인증 및 자동 검토")
    body("4) 친구, 그룹 및 다른 회원과의 상호작용 제공")
    body("5) 신고 접수, 운영 기준 적용 및 서비스 보호")
    body("6) 알림 발송과 문의 처리")
    body("7) 오류 확인, 부정 이용 방지 및 서비스 개선")
    body()
    body("개인정보의 이용 목적이 변경되는 경우 관련 법령에 따라 별도의 동의를 받거나 필요한 조치를 합니다.")
    body()
    heading("2. 처리하는 개인정보 항목")
    body()
    body("[회원가입 및 로그인 시 필수 항목]")
    body()
    body("• 소셜 로그인 제공자")
    body("• 소셜 계정 식별자")
    body("• 이메일 주소")
    body("• 닉네임")
    body()
    body("[회원이 선택하여 등록하는 항목]")
    body()
    body("- 프로필 사진")
    body("- 인증 사진과 인증 관련 내용")
    body("- 문의 내용 및 첨부 자료")
    body()
    body("[서비스 이용 과정에서 처리하는 항목]")
    body()
    body("- 생성하거나 참여한 루틴의 이름, 설명, 일정 및 참여 정보")
    body("- 인증 날짜, 인증 결과 및 수행 기록")
    body("- 친구 및 그룹 관계")
    body("- 쿡쿡 등 회원 간 상호작용 기록")
    body("- 앱 내 재화의 지급 및 사용 기록")
    body("- 신고 대상, 신고 유형, 신고 사유 및 처리 기록")
    body("- 문의 내용과 처리 기록")
    body()
    body("[서비스 이용 과정에서 자동으로 생성될 수 있는 항목]")
    body()
    body("- Firebase Cloud Messaging 알림 전송용 토큰")
    body("- 접속 일시, 서비스 이용 기록 및 오류 기록")
    body()
    heading("3. 개인정보의 수집 방법")
    body()
    body("리루티는 다음 방법으로 개인정보를 수집합니다.")
    body()
    body("1) 회원이 소셜 로그인과 프로필 설정 과정에서 직접 입력하거나 전송하는 방법")
    body("2) 회원이 루틴, 인증 사진, 신고 및 문의 기능을 이용하면서 직접 등록하는 방법")
    body("3) 회원이 서비스를 이용하는 과정에서 자동으로 생성되는 정보를 수집하는 방법")
    body()
    heading("4. 개인정보의 처리 및 보유 기간")
    body()
    body("1) 회원가입 및 계정 정보: 회원 탈퇴 시까지")
    body("2) 프로필 사진과 인증 사진: 회원이 삭제하거나 회원 탈퇴 시까지")
    body("3) 공동 루틴의 수행 여부와 날짜: 해당 공동 기록이 유지되는 기간. 회원 탈퇴 후에는 작성자를 직접 식별할 수 없도록 \"탈퇴한 사용자\"로 표시할 수 있습니다.")
    body("4) 신고 기록: 신고 처리 완료일부터 1년")
    body("5) 문의 기록: 문의 처리 완료일부터 1년")
    body("6) 접속 및 오류 기록: 생성일부터 3개월")
    body("7) 알림 전송용 토큰: 로그아웃, 회원 탈퇴 또는 토큰이 유효하지 않게 될 때까지")
    body()
    body("보유 기간이 끝나거나 처리 목적이 달성된 개인정보는 지체 없이 삭제합니다. 다만 관련 법령에 따라 일정 기간 보관해야 하는 정보는 해당 기간 동안 다른 정보와 분리하여 보관합니다.")
    body()
    heading("5. 개인정보의 제3자 제공")
    body()
    body("리루티는 회원의 개인정보를 원칙적으로 제3자에게 제공하지 않습니다. 법령에 근거가 있거나 회원이 별도로 동의한 경우에는 제공받는 사람, 제공 목적, 제공 항목 및 보유 기간을 사전에 안내합니다.")
    body()
    body("서비스 제공을 위해 외부 업체가 리루티를 대신하여 개인정보를 처리하는 경우는 아래의 개인정보 처리업무 위탁에 해당합니다.")
    body()
    heading("6. 다른 회원에게 공개되는 정보")
    body()
    body("회원이 공동 루틴, 친구 또는 그룹 기능을 이용하면 다음 정보가 다른 회원에게 표시될 수 있습니다.")
    body()
    body("• 닉네임과 프로필 사진")
    body("• 참여 중인 공동 루틴")
    body("• 루틴 인증 여부와 인증 시간")
    body("• 회원이 공유하도록 등록한 인증 사진")
    body("• 쿡쿡 등 서비스 내 상호작용 정보")
    body()
    body("회원은 다른 사람의 개인정보나 얼굴이 포함된 사진을 당사자의 동의 없이 등록해서는 안 됩니다.")
    body()
    heading("7. 개인정보 처리업무의 위탁")
    body()
    body("리루티는 서비스 제공을 위해 다음 외부 업체에 개인정보 처리업무를 맡기고 있습니다.")
    body()
    body("- Amazon Web Services, Inc.: 서버 운영과 이미지 저장")
    body("- Google LLC: Firebase Cloud Messaging을 이용한 앱 알림 전송")
    body("- Anthropic, PBC: 인증 사진의 루틴 관련성 자동 검토")
    body()
    body("리루티는 각 업체가 위탁 목적에 필요한 범위에서만 개인정보를 처리하도록 관리하며, 위탁 내용이 변경되는 경우 본 개인정보 처리방침을 통해 안내합니다.")
    body()
    heading("8. 개인정보의 국외 이전")
    body()
    body("[Anthropic]")
    body()
    body("- 이전받는 업체: Anthropic, PBC")
    body("- 이전 목적: 인증 사진의 루틴 관련성 자동 검토")
    body("- 이전 항목: 축소된 인증 사진, 루틴 이름 및 설명")
    body("- 이전 시점과 방법: 인증 요청 시 암호화된 통신을 통해 전송")
    body("- 처리 지역: 미국, 유럽, 아시아 및 호주 지역이며 데이터는 미국에 저장될 수 있음")
    body("- 보유 기간: API 입력 및 출력은 원칙적으로 수신 또는 생성 후 30일 이내 삭제")
    body("- 이전 거부 방법: 인증 사진을 등록하지 않음")
    body("- 거부 시 영향: 사진 인증 기능을 이용할 수 없음")
    body()
    body("[Google Firebase]")
    body()
    body("- 이전받는 업체: Google LLC 및 관련 처리업체")
    body("- 이전 목적: 푸시 알림 전송")
    body("- 이전 항목: Firebase Cloud Messaging 알림 전송용 토큰")
    body("- 이전 시점과 방법: 알림 기능 등록 및 전송 시 암호화된 통신을 통해 전송")
    body("- 처리 지역: 미국을 포함하여 Google 또는 관련 처리업체의 데이터 처리 시설이 위치한 국가")
    body("- 보유 기간: 알림 전송에 필요한 기간 또는 삭제 요청 후 Google의 활성·백업 시스템에서 삭제될 때까지")
    body("- 이전 거부 방법: 기기 설정에서 알림 권한을 허용하지 않음")
    body("- 거부 시 영향: 푸시 알림을 받을 수 없으나 다른 기능은 이용할 수 있음")
    body()
    body("회원은 위와 같은 국외 이전을 원하지 않는 경우 해당 기능을 이용하지 않거나 앱 내 \"문의하기\"를 통해 관련 처리를 요청할 수 있습니다.")
    body()
    heading("9. 인증 사진의 자동 검토")
    body()
    body("1) 회원이 등록한 인증 사진은 해당 루틴과 관련된 사진인지 확인하기 위해 자동화된 방식으로 검토될 수 있습니다.")
    body("2) 자동 검토를 위해 축소된 인증 사진과 루틴 이름 및 설명이 Anthropic에 전송됩니다.")
    body("3) 리루티는 인증 사진을 AI 모델 학습 목적으로 이용하지 않습니다.")
    body("4) 자동 검토 결과에 따라 인증이 승인, 반려 또는 보류될 수 있습니다.")
    body("5) 자동 검토 결과에 이의가 있는 회원은 앱 내 \"문의하기\"를 통해 재검토를 요청할 수 있습니다.")
    body()
    heading("10. 개인정보의 파기")
    body()
    body("1) 보유 기간이 끝나거나 처리 목적이 달성된 개인정보는 지체 없이 파기합니다.")
    body("2) 전자 파일은 복구하기 어려운 방법으로 삭제합니다.")
    body("3) 법령에 따라 계속 보관해야 하는 정보는 다른 개인정보와 분리하여 보관합니다.")
    body()
    heading("11. 회원의 권리와 행사 방법")
    body()
    body("회원은 자신의 개인정보에 대해 다음 권리를 행사할 수 있습니다.")
    body()
    body("1) 개인정보 열람 요청")
    body("2) 잘못된 정보의 정정 요청")
    body("3) 개인정보 삭제 요청")
    body("4) 개인정보 처리 정지 또는 동의 철회")
    body("5) 회원 탈퇴")
    body()
    body("관련 요청은 앱의 회원 탈퇴 기능, 앱 내 \"문의하기\" 또는 liroutisupport@gmail.com을 통해 접수할 수 있습니다. 리루티 운영팀은 요청한 사람이 회원 본인인지 확인한 후 관련 법령에 따라 처리합니다.")
    body()
    heading("12. 만 14세 미만 이용자")
    body()
    body("리루티는 만 14세 미만인 사람의 회원가입을 허용하지 않으며, 만 14세 미만인 사람의 개인정보를 의도적으로 수집하지 않습니다.")
    body()
    heading("13. 개인정보의 안전성 확보 조치")
    body()
    body("리루티 운영팀은 개인정보 보호를 위해 다음 조치를 시행합니다.")
    body()
    body("1) 개인정보에 접근할 수 있는 인원 최소화")
    body("2) 계정 및 접근 권한 관리")
    body("3) 전송 구간 암호화")
    body("4) 인증 사진의 접근 제한")
    body("5) 접속 기록 확인 및 보안 점검")
    body("6) 외부 서비스 인증 정보와 비밀키의 별도 관리")
    body()
    heading("14. 개인정보 보호 문의 및 권익 침해 구제")
    body()
    body("[개인정보 보호 문의]")
    body()
    body("- 담당 부서: 리루티 운영팀")
    body("- 이메일: liroutisupport@gmail.com")
    body("- 문의 방법: 앱 내 \"문의하기\"")
    body()
    body("개인정보 침해에 대한 상담이나 구제가 필요한 경우 다음 기관에 문의할 수 있습니다.")
    body()
    body("- 개인정보침해 신고센터: 국번 없이 118, https://privacy.kisa.or.kr")
    body("- 개인정보분쟁조정위원회: 1833-6972, https://www.kopico.go.kr")
    body()
    heading("15. 개인정보 처리방침의 변경")
    body()
    body("본 개인정보 처리방침이 변경되는 경우 적용일과 변경 사유를 서비스 내 공지사항을 통해 안내합니다. 일반적인 변경 사항은 적용일 7일 전부터 안내하며, 회원의 권리에 중대한 영향을 주는 변경 사항은 적용일 30일 전부터 안내합니다.")
    body()
    body("부칙")
    body()
    body("본 개인정보 처리방침은 2026년 8월 21일부터 시행합니다.")
}

/** 신고 및 운영 정책. Figma node `6008:18127`. */
val ReportPolicyLines: List<PolicyLine> = policyLines {
    title("리루티 신고 및 운영 정책")
    body()
    body("시행일: 2026년 8월 21일")
    body()
    heading("1. 목적")
    body()
    body("본 정책은 리루티 회원이 안전하고 원활하게 서비스를 이용할 수 있도록 콘텐츠 등록 기준, 신고 방법 및 신고된 콘텐츠의 처리 기준을 안내하는 것을 목적으로 합니다.")
    body()
    heading("2. 등록할 수 없는 콘텐츠")
    body()
    body("회원은 다음에 해당하는 인증 사진이나 콘텐츠를 등록해서는 안 됩니다.")
    body()
    body("1) 루틴의 내용과 관계없는 콘텐츠")
    body("2) 이전 인증에 사용한 사진을 반복하여 등록한 콘텐츠")
    body("3) 다른 사람이 촬영하거나 등록한 사진을 도용한 콘텐츠")
    body("4) 다른 사람의 개인정보나 얼굴이 동의 없이 포함된 콘텐츠")
    body("5) 욕설, 혐오 표현, 성적 표현 또는 폭력적인 내용이 포함된 콘텐츠")
    body("6) 광고, 홍보 또는 반복적인 도배성 콘텐츠")
    body("7) 불법 행위를 포함하거나 관련 법령을 위반하는 콘텐츠")
    body("8) 그 밖에 다른 회원에게 피해를 주거나 서비스 운영을 방해하는 콘텐츠")
    body()
    heading("3. 인증물의 자동 검토")
    body()
    body("1) 등록된 인증 사진은 해당 루틴과 관련된 사진인지 자동으로 검토될 수 있습니다.")
    body("2) 루틴과 관련이 없는 것으로 판단된 인증물은 반려되거나 표시되지 않을 수 있습니다.")
    body("3) 자동 검토를 완료하지 못한 경우 인증 처리가 일시적으로 보류될 수 있습니다.")
    body("4) 자동 검토 결과에 이의가 있는 회원은 앱 내 \"문의하기\"를 통해 재검토를 요청할 수 있습니다.")
    body()
    heading("4. 신고 방법")
    body()
    body("1) 회원은 운영 기준을 위반한 것으로 의심되는 다른 회원의 인증물을 신고할 수 있습니다.")
    body("2) 동일한 인증물은 회원 한 명당 한 번만 신고할 수 있습니다.")
    body("3) 신고 유형은 다음과 같이 구분합니다.")
    body()
    body("• 루틴과 관계없는 인증")
    body("• 재사용한 사진")
    body("• 다른 사람의 사진 도용")
    body("• 광고 또는 도배")
    body("• 기타 운영 기준 위반")
    body()
    body("4) \"기타 운영 기준 위반\"을 선택한 경우 구체적인 신고 사유를 작성해야 합니다.")
    body("5) 접수된 신고는 서비스에서 직접 취소할 수 없습니다. 잘못 신고한 경우 앱 내 \"문의하기\"를 통해 알려 주세요.")
    body()
    heading("5. 신고된 인증물의 처리")
    body()
    body("1) 신고가 접수되면 해당 인증물은 신고한 회원의 화면에서 즉시 숨겨집니다.")
    body("2) 서로 다른 회원 3명의 신고가 누적되면 해당 인증물은 전체 회원에게 자동으로 숨겨집니다.")
    body("3) 신고 누적에 따른 자동 숨김은 운영 기준 위반 여부에 대한 최종 판단을 의미하지 않습니다.")
    body("4) 인증물이 전체 숨김 처리되면 해당 인증물을 등록한 회원에게 알림이 발송될 수 있습니다.")
    body("5) 신고자의 개인정보와 구체적인 신고 내용은 신고 대상 회원에게 공개하지 않습니다.")
    body("6) 신고자에게는 별도의 처리 결과가 제공되지 않을 수 있습니다.")
    body()
    heading("6. 운영 기준 위반 콘텐츠에 대한 조치")
    body()
    body("1) 운영 기준을 위반하거나 다른 사람의 권리를 침해한 콘텐츠는 숨김 또는 삭제될 수 있습니다.")
    body("2) 관련 법령을 위반하거나 다른 회원에게 중대한 피해를 줄 우려가 있는 콘텐츠에는 필요한 추가 조치가 적용될 수 있습니다.")
    body("3) 조치 여부와 범위는 콘텐츠의 내용, 피해 정도 및 반복 여부 등을 고려하여 정합니다.")
    body()
    heading("7. 허위 신고 및 신고 기능 악용")
    body()
    body("1) 다른 회원에게 불이익을 주기 위한 허위 신고를 해서는 안 됩니다.")
    body("2) 여러 계정을 이용하거나 반복적인 방법으로 신고 기능을 악용해서는 안 됩니다.")
    body("3) 신고 기능을 악용한 것으로 확인되면 관련 법령과 운영 기준에 따라 필요한 조치가 적용될 수 있습니다.")
    body()
    heading("8. 재검토 요청")
    body()
    body("1) 인증물 숨김이나 자동 검토 결과에 이의가 있는 회원은 재검토를 요청할 수 있습니다.")
    body("2) 재검토 요청은 앱 내 \"문의하기\" 또는 liroutisupport@gmail.com을 통해 접수할 수 있습니다.")
    body("3) 요청할 때는 계정을 확인할 수 있는 정보, 대상 인증물 및 이의 사유를 함께 제출해야 합니다.")
    body("4) 리루티 운영팀은 접수된 내용을 확인한 뒤 가능한 조치와 처리 결과를 안내합니다.")
    body()
    heading("9. 정책의 변경")
    body()
    body("운영 환경이나 서비스 기능이 변경되는 경우 본 정책도 변경될 수 있습니다. 중요한 변경 사항은 적용 전에 공지사항을 통해 안내합니다.")
    body()
    body("부칙")
    body()
    body("본 정책은 2026년 8월 21일부터 시행합니다.")
}

/** 오픈소스 라이선스. Figma node `6008:18160`. */
val OpenSourceLicenseLines: List<PolicyLine> = policyLines {
    title("리루티 오픈소스 라이선스")
    body()
    body("리루티는 다음 오픈소스 소프트웨어를 사용합니다. 각 소프트웨어의 저작권은 해당 개발자와 기여자에게 있으며, 아래의 라이선스 조건에 따라 사용됩니다.")
    body()
    body("1. 오픈소스 라이브러리")
    body()
    body("1-1. Apache License 2.0")
    body()
    body("다음 소프트웨어에는 Apache License 2.0이 적용됩니다.")
    body()
    body("• AndroidX 및 Jetpack Compose")
    body("• AndroidX Core 1.17.0")
    body("• Activity Compose 1.13.0")
    body("• Lifecycle Runtime/ViewModel KTX 2.9.4")
    body("• Lifecycle ViewModel/Runtime Compose 2.9.2")
    body("• Navigation Compose 2.9.3")
    body("• DataStore Preferences 1.2.1")
    body("• CameraX 1.6.1")
    body("• AppCompat 1.7.1")
    body("• Credentials 1.6.0")
    body("• Jetpack Compose BOM 2024.09.00")
    body("• Kotlin Standard Library 2.2.10")
    body("• Kotlinx Coroutines 1.10.2")
    body("• Retrofit 2.11.0")
    body("• OkHttp 4.12.0")
    body("• Okio 3.9.1")
    body("• Gson 2.10.1")
    body("• Hilt 2.57 및 Dagger 2.59")
    body("• Hilt Navigation Compose 1.2.0")
    body("• Material Components for Android 1.13.0")
    body("• Coil 2.7.0")
    body("• Firebase Android SDK BOM 33.14.0")
    body()
    body("Apache License 2.0 전문:")
    body("https://www.apache.org/licenses/LICENSE-2.0")
    body()
    body("관련 저장소:")
    body("- AndroidX: https://github.com/androidx/androidx/blob/androidx-main/LICENSE.txt")
    body("- Kotlin: https://github.com/JetBrains/kotlin/blob/master/license/LICENSE.txt")
    body("- Retrofit: https://github.com/square/retrofit/blob/trunk/LICENSE.txt")
    body("- OkHttp: https://github.com/square/okhttp/blob/master/LICENSE.txt")
    body("- Dagger: https://github.com/google/dagger/blob/master/LICENSE.txt")
    body("- Coil: https://github.com/coil-kt/coil/blob/main/LICENSE.txt")
    body("- Firebase Android SDK: https://github.com/firebase/firebase-android-sdk/blob/main/LICENSE")
    body()
    body("1-2. MIT License")
    body()
    body("[Krossbow 9.3.0]")
    body()
    body("Copyright (c) 2019-2025 Joffrey Bion")
    body()
    body("Krossbow는 MIT License에 따라 사용됩니다.")
    body()
    body("라이선스 전문:")
    body("https://github.com/joffrey-bion/krossbow/blob/main/LICENSE")
    body()
    body("1-3. GNU General Public License v2 with Classpath Exception")
    body()
    body("[desugar_jdk_libs 2.1.5]")
    body()
    body("Android 이전 버전에서 일부 Java API를 지원하기 위해 desugar_jdk_libs를 사용합니다. 해당 소프트웨어의 일부 구성요소에는 GNU General Public License Version 2와 Classpath Exception이 적용됩니다.")
    body()
    body("라이선스 전문:")
    body("https://github.com/google/desugar_jdk_libs/blob/master/LICENSE")
    body()
    body("2. 외부 SDK 및 서비스")
    body()
    body("다음 항목은 오픈소스 라이브러리 고지와 별도로 각 제공자의 이용약관, 개인정보 처리방침 및 라이선스 조건이 적용되는 외부 SDK 또는 서비스입니다.")
    body()
    body("- Kakao SDK for Android 2.24.0: 소셜 로그인")
    body("- Google Identity 1.2.0 및 Google Play services: Google 로그인")
    body("- Firebase Cloud Messaging: 푸시 알림 전송")
    body("- Amazon Web Services: 서버 운영 및 이미지 저장")
    body("- Anthropic API: 인증 사진의 루틴 관련성 자동 검토")
    body("- PortOne Android SDK 0.2.3: 결제 연동")
    body()
    body("관련 안내:")
    body("- Kakao SDK: https://developers.kakao.com/docs/ko/android/download")
    body("- Google Identity: https://developers.google.com/identity")
    body("- Firebase: https://firebase.google.com/terms")
    body("- Amazon Web Services: https://aws.amazon.com/service-terms/")
    body("- Anthropic: https://www.anthropic.com/legal/commercial-terms")
    body()
    body("3. 안내")
    body()
    body("이 문서는 현재 프로젝트에서 수동으로 관리하는 라이브러리와 버전 정보를 기준으로 작성되었습니다. 오픈소스 구성요소와 버전은 앱 업데이트에 따라 변경될 수 있으므로, 배포 전에 실제 앱에 포함된 의존성과 각 라이선스 고지 내용을 다시 확인하여 갱신합니다.")
    body()
}

/** 코인 및 환불 정책. Figma node `6008:18226`. */
val CoinRefundPolicyLines: List<PolicyLine> = policyLines {
    title("리루티 코인 및 환불 정책")
    body()
    body("시행일: 2026년 8월 21일")
    body()
    heading("1. 목적")
    body()
    body("본 정책은 리루티에서 제공하는 앱 내 재화의 획득, 사용, 회수 및 환불 기준을 안내하는 것을 목적으로 합니다.")
    body()
    heading("2. 앱 내 재화")
    body()
    body("1) 리루티는 서비스 이용을 위해 다이아와 토파즈 등의 가상 재화를 제공할 수 있습니다.")
    body("2) 앱 내 재화는 루틴 수행, 보상 수령, 재화 교환 및 서비스 이벤트 등을 통해 획득할 수 있습니다.")
    body("3) 재화의 지급 수량, 교환 비율 및 사용처는 앱 화면에서 안내합니다.")
    body("4) 데모 운영 상황에 따라 재화의 종류, 지급 기준, 교환 비율 또는 사용처가 변경될 수 있습니다.")
    body()
    heading("3. 재화의 사용")
    body()
    body("1) 회원은 보유한 재화를 리루티에서 제공하는 기능과 아이템에 사용할 수 있습니다.")
    body("2) 정상적으로 사용이 완료된 재화는 원칙적으로 복구되지 않습니다.")
    body("3) 시스템 오류로 재화가 잘못 차감되거나 지급되지 않은 경우 앱 내 \"문의하기\"를 통해 확인과 복구를 요청할 수 있습니다.")
    body()
    heading("4. 재화의 성격과 양도 제한")
    body()
    body("1) 앱 내 재화는 법정통화가 아니며 리루티 안에서만 사용할 수 있는 가상의 수단입니다.")
    body("2) 앱 내 재화는 서비스 밖에서 사용할 수 없으며 현금으로 교환할 수 없습니다.")
    body("3) 회원은 재화를 다른 회원에게 판매하거나 양도할 수 없습니다.")
    body()
    heading("5. 결제 및 환불")
    body()
    body("1) 현재 데모 서비스에서는 실제 금액을 결제하는 유료 충전 기능을 제공하지 않습니다.")
    body("2) 데모에서 무료로 지급되는 재화는 현금 환불 대상에 해당하지 않습니다.")
    body("3) 추후 실제 결제 기능을 제공하는 경우 결제 취소, 청약 철회 및 환불 기준을 별도로 마련하여 유료 기능 제공 전에 안내합니다.")
    body()
    heading("6. 재화의 회수 및 소멸")
    body()
    body("1) 오류, 조작 또는 부정한 방법으로 획득한 재화는 회수될 수 있습니다.")
    body("2) 회원이 탈퇴하면 보유한 재화는 모두 소멸하며 복구되지 않습니다.")
    body("3) 데모 종료, 테스트 데이터 초기화 또는 서비스 개편 과정에서 재화가 초기화될 수 있습니다.")
    body("4) 재화 초기화가 예정된 경우 가능한 범위에서 공지사항을 통해 안내합니다.")
    body()
    heading("7. 문의")
    body()
    body("재화의 지급, 차감 또는 사용과 관련한 문의는 앱 내 \"문의하기\" 또는 liroutisupport@gmail.com을 통해 접수할 수 있습니다.")
    body()
    body("부칙")
    body()
    body("본 정책은 2026년 8월 21일부터 시행합니다.")
}
